# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='tag/'),
            preserve_default=False,
        ),
    ]
